### ISSUE TITLE
Tests fail on Windows If Run in Certain Dirs

### ISSUE THREAD

**Issue by genio** [plicease/Test-Version#10]
I have portable Strawberry Perl in ```C:\Strawberry\5.18.4.1\```
I also make use of a local::lib in ```C:\Strawberry\ll_5.18.4.1_normal\```

So, when I try to install Test::Version with ```cpanm Test::Version```, the test suite will be running from a rather strange directory: ```C:\STRAWB~1\5184~1.1\data\.cpanm\work\1524619864.11956\Test-Version-2.07```

The current ```untaint_pattern``` doesn't allow for the DOS shortname (8.3) tilde syntax. When the tests run from this directory, many of them fail with: "insecure cwd in find(depth) at...". To fix this, the ```untaint_pattern``` needs to allow the backslash ```\\``` and tilde ```~```.

line 216:
```perl
    ($^O eq 'MSWin32' ? (untaint_pattern => qr|^(([a-zA-Z]:)?[-+@\w./\\~]+)$|x) : ()),
```

I can't guarantee that will fix _all_ odd Windows directory patterns, but it allows my odd setup to pass.

Thanks,
Chase

**Comment by plicease** [comment]
I put the tests into taint mode because someone sent me a patch making Test-Version work in taint mode (almost, it didn't work on windows), and I didn't want to immediately break that support in a future version unintentionally.  Possibly a mistake?  Possibly generated extra unnecessary work?  Maybe.  Anyway, I think I have it working for the common Windows cases in `2.08_02`, can you try that?

**Comment by genio** [comment]
```powershell
PS C:\Users\cwhitener\chase\p5-UV> cpanm --test-only Test::Version@2.08_02
--> Working on Test::Version
Fetching http://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Test-Version-2.08_02.tar.gz ... OK
Configuring Test-Version-2.08_02 ... OK
Building and testing Test-Version-2.08_02 ... OK
Successfully tested Test-Version-2.08_02
PS C:\Users\cwhitener\chase\p5-UV>
```

**Comment by plicease** [comment]
Cool.  Doing a production release now. 2.09 should address this.
